# Generated by Django 5.2.7 on 2025-10-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={},
        ),
    ]
